language: ruby
rvm:
  - 2.3.0
script:
  - bundle exec rake db:migrate
  - bundle exec rake
  
deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"
    
    travis encrypt $(heroku auth:token) --add deploy.api_key
