# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e89db036a9779c7091ba9f4133f27f79ea212558dff347f0eb84d7a94924fcddb361c8315e7b68a2781c092a36193d5df7148cb2ac5c1a50913d87a11e542dab

test:
  secret_key_base: 0dc800cf66a5da20587ca6835d8167f18439385a4e8bc1d3d841eaf8b141bf3fd22f4257fba2ccd5758d3b0187e3e3b032acb4836fa8004a0c87be21e0f76345

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
